_GeneralUpdate : _Settings_reset : 
	File : run.py
	Line no. : 361
	Thursday : 20:10
	
